// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqNL0cPUS0hthRLh3OQvOIGueFDZOMLQ0',
    appId: '1:455014733188:web:095513f7ef0303e0a1f9d1',
    messagingSenderId: '455014733188',
    projectId: 'myscheduleplanner-e22f3',
    authDomain: 'myscheduleplanner-e22f3.firebaseapp.com',
    storageBucket: 'myscheduleplanner-e22f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2d99hNE2NRiGiKobbmvgndlBfFxkYGik',
    appId: '1:455014733188:android:469e8f6c75823770a1f9d1',
    messagingSenderId: '455014733188',
    projectId: 'myscheduleplanner-e22f3',
    storageBucket: 'myscheduleplanner-e22f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxXIFOKFiich2Dsc06-ogPCg8qTy09hwM',
    appId: '1:455014733188:ios:d8e53fcbff8720aaa1f9d1',
    messagingSenderId: '455014733188',
    projectId: 'myscheduleplanner-e22f3',
    storageBucket: 'myscheduleplanner-e22f3.firebasestorage.app',
    iosBundleId: 'com.myplanscheduler.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxXIFOKFiich2Dsc06-ogPCg8qTy09hwM',
    appId: '1:455014733188:ios:d8e53fcbff8720aaa1f9d1',
    messagingSenderId: '455014733188',
    projectId: 'myscheduleplanner-e22f3',
    storageBucket: 'myscheduleplanner-e22f3.firebasestorage.app',
    iosBundleId: 'com.myplanscheduler.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqNL0cPUS0hthRLh3OQvOIGueFDZOMLQ0',
    appId: '1:455014733188:web:88fe1b24ccc196cca1f9d1',
    messagingSenderId: '455014733188',
    projectId: 'myscheduleplanner-e22f3',
    authDomain: 'myscheduleplanner-e22f3.firebaseapp.com',
    storageBucket: 'myscheduleplanner-e22f3.firebasestorage.app',
  );
}
